#
# eChempad is a suite of web services oriented to manage the entire
# data life-cycle of experiments and assays from Experimental
# Chemistry and related Science disciplines.
#
# Copyright (C) 2021 - present Institut Català d'Investigació Química (ICIQ)
#
# eChempad is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#

# prod contains properties used during production
# These properties work when running the software in containers and in our deployment server

---
version: "3.9"
services:
  echempad_app:
    image: aleixmt/echempad:latest
    pull_policy: always
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - "-Dspring.profiles.active=prod,secrets"
    ports:
      - "0.0.0.0:80:8081"
    volumes:  # Mount secret files (DATAVERSE_KEY.txt and SIGNALS_KEY.txt)
      - ./src/main/resources/secrets/DATAVERSE_KEY.txt:/app/target/classes/secrets/DATAVERSE_KEY.txt
      - ./src/main/resources/secrets/SIGNALS_KEY.txt:/app/target/classes/secrets/SIGNALS_KEY.txt
    restart: unless-stopped

  postgres_db:
    image: postgres
    pull_policy: always
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=chemistry
      - POSTGRES_USER=amarine
      - POSTGRES_DB=eChempad
    ports:
      - "0.0.0.0:8080:5432"
    restart: unless-stopped
