#
# eChempad is a suite of web services oriented to manage the entire
# data life-cycle of experiments and assays from Experimental
# Chemistry and related Science disciplines.
#
# Copyright (C) 2021 - present Institut Català d'Investigació Química (ICIQ)
#
# eChempad is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#


# Contains config used during development using docker containers
# These properties work when running the software in containers and in a development machine

---
services:

  postgres_db:
    image: postgres:latest
    pull_policy: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/ECHEMPAD_DB_PASSWORD
      - POSTGRES_USER=eChempad
      - POSTGRES_DB=eChempad
      # Change default location of database data files for persisting data
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      # Mount .sql files for db schema initialization
      - ./src/main/resources/SQL:/docker-entrypoint-initdb.d
      # Mount volume for persisting data
      - pgdata:/var/lib/postgresql/data
    secrets:
      - ECHEMPAD_DB_PASSWORD


  echempad-cas:
    image: aleixmt/echempad-cas:latest
    build:
      context: ../eChempad-CAS
      dockerfile: Dockerfile
    pull_policy: always
    environment:  # We always need to load secrets or there will be no functionality
      - SPRING_PROFILES_ACTIVE=standalone,ldap,orcid,db,dev,prod,container,secrets
    ports:
      - "0.0.0.0:8443:8443"
      - "8080:8080"
    volumes: # Mount secrets configuration file
      - ${PWD}/src/main/resources/secrets/cas_secrets/cas_secrets.properties:/etc/cas/config/secrets.properties
    depends_on:
      postgres_db:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-check-certificate --no-verbose --tries=1 --spider https://localhost:8443/cas/login" ]
      interval: 20s
      retries: 10
      timeout: 60s
      start_period: 5s

  echempad-app:
    image: aleixmt/echempad:latest
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    environment:
      - TZ=Etc/UTC
      - SPRING_PROFILES_ACTIVE=container
      - WORDPRESS_DB_USER: wordpress
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      echempad-cas:
        condition: service_healthy
      postgres_db:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-check-certificate --no-verbose --tries=1 --spider https://localhost:8081/health" ]
      interval: 20s
      retries: 10
      timeout: 60s
      start_period: 5s
    secrets:
      - ECHEMPAD_DB_PASSWORD
      - ECHEMPAD_APP_CERT
      - ECHEMPAD_CAS_CERT
      - ECHEMPAD_DATAVERSE_TOKEN
      - ECHEMPAD_SIGNALS_TOKEN

secrets:
  ECHEMPAD_DB_PASSWORD:
    environment: "ECHEMPAD_DB_PASSWORD"
  ECHEMPAD_APP_CERT:
    environment: "ECHEMPAD_APP_CERT"
  ECHEMPAD_CAS_CERT:
    environment: "ECHEMPAD_CAS_CERT"
  ECHEMPAD_DATAVERSE_TOKEN:
    environment: "ECHEMPAD_DATAVERSE_TOKEN"
  ECHEMPAD_SIGNALS_TOKEN:
    environment: "ECHEMPAD_SIGNALS_TOKEN"
  ECHEMPAD_CAS_LDAP_TOKEN:
    environment: "ECHEMPAD_LDAP_TOKEN"

volumes:
  pgdata:
