name: ci


#on:
#  push:
#    branches:
#      - "master"

on: [push, delete]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/echempad:latest

  deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Download docker-compose.yml
        run: wget https://raw.githubusercontent.com/AleixMT/eChempad/master/docker-compose.yaml -O docker-compose.yaml

      - name: Stop eChempad container
        run: docker-compose down

      - name: restart eChempad container with new image, which will be automatically pulled
        run: docker-compose up -d