name: ci

# Trigger event on every push / delete event, no matter the branch
# on: [push, delete]

# Trigger event on every push / delete event, only in master branch
on:
  push:
    branches:
      - "master"
  delete:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/echempad:latest

  deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download docker-compose.yml
        run: mv docker-compose.ci.yaml docker-compose.yaml
          
      - name: Stop eChempad container
        run: docker-compose down

      - name: Force pulling of the images or they would not be updated
        run: docker-compose pull

      - name: restart eChempad container with new image, which will be automatically pulled
        run: docker-compose up -d